apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zomboid-cert
  namespace: ${namespace}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  secretName: zomboid-ssl
  renewBefore: 360h # 15d
  dnsNames:
    - ${subdomain}.${domain}
    - map.zomboid.${domain}
  issuerRef:
    name: ${cert_issuer}
    kind: ClusterIssuer
