apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zomboid-cert
  namespace: zomboid
  annotations:
    cert-manager.io/cluster-issuer: zerossl-prod
spec:
  secretName: zomboid-ssl
  renewBefore: 360h # 15d
  dnsNames:
    - zomboid.dragonfruit.dev
    - map.zomboid.dragonfruit.dev
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
