# Traefik has two UDP entrypoints defined so that these ingressroutes work
# Note no RCON ingressroute, I'd rather have internal access to do that
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: server-a
  namespace: zomboid
spec:
  entryPoints:
    - zomboid-a
  routes:
    - services:
        - name: zomboid
          port: 16261
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: server-b
  namespace: zomboid
spec:
  entryPoints:
    - zomboid-b
  routes:
    - services:
        - name: zomboid
          port: 8766
