apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zomboid
  namespace: flux-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: kv/k8s/zomboid/secret
