apiVersion: v1
kind: Service
metadata:
  name: zomboid
spec:
  selector:
    app: zomboid
  type: LoadBalancer
  ports:
    - name: steam
      protocol: UDP
      port: 8766
    - name: rcon
      port: 27015
    - name: game
      protocol: UDP
      port: 16261
---
apiVersion: v1
kind: Service
metadata:
  name: zomboid-headless
spec:
  selector:
    app: zomboid
  type: ClusterIP
  ports:
    - name: steam
      protocol: UDP
      port: 8766
    - name: rcon
      port: 27015
    - name: game
      protocol: UDP
      port: 16261
