apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zomboid
  labels:
    app: zomboid
spec:
  replicas: 0
  serviceName: zomboid
  selector:
    matchLabels:
      app: zomboid
  # Zomboid is very IO heavy it seems, NFS doesn't really do well.
  # Local-path + dedicated K8s node + careful rclone to B2 for backups
  # K8s node specs: 4 vcpu, 12G ram, Intel S3710 SSD backing the VM
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
  template:
    metadata:
      labels:
        app: zomboid
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "gotm"
                    operator: In
                    values:
                      - "true"
      # K8s node is labeled with gotm (game of the month)
      # Dedicated, higher power k8s node dedicated for game servers
      tolerations:
        - key: "gotm"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"
      # K8s node is also tainted with gotm, so that only the gotm pod + logging and metrics and crap
      containers:
        - name: zomboid
          image: docker.io/renegademaster/zomboid-dedicated-server:latest
          resources:
            requests:
              cpu: 2
          envFrom:
            - secretRef:
                name: zomboid
          livenessProbe:
            tcpSocket:
              port: 27015
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 27015
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 600
          ports:
            - containerPort: 27015
              protocol: TCP
            - containerPort: 8766
              protocol: UDP
            - containerPort: 16261
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /home/steam/ZomboidDedicatedServer
            - name: config
              mountPath: /home/steam/Zomboid
